const Constant = {
    ACTION: {
        USER: 'user/',
        ADMIN: 'admin/',
        PING: 'ping',
        STORE: 'store/',
        DEFAULT: 'DEFAULT/',
        CATEGORY: 'category/',
        CATEGORYLIST: 'list/',
        CATEGORYDETAIL: 'categoryDetail/',
        CONTENT: 'content/',
        PAGES: 'pages/',
        PAGEDETAIL: 'pageDetail/',
        PRODUCT: 'product/',
        FEATUREDITEM: 'featuredItem/',
        PRODUCTS: 'products/',
        PRODUCTLIST: 'productList/',
        PRODUCTDETAIL: 'productDetail/',
        PRODUCTREVIEW: 'productReview/',
        CART: 'cart/',
        GETUSERCART: 'getUserCart/',
        ADDCART: 'addCart/',
        UPDATECART: 'updateCart/',
        DELETECART: 'deleteCart/',
        CARTS: 'cart',
        PRICE: 'price/',
        CUSTOMER: 'customer/',
        LOGIN: 'login/',
        CUSTOMERS: 'customers/',
        MANUFACTURERS: 'manufacturers/',
        VARIANTS: 'variants/',
        CONFIG: 'config/',
        COUNTRY: 'country/',
        ZONES: 'zone/',
        AUTH: 'auth/',
        PROFILE: 'profile/',
        SHIPPING: 'shipping/',
        GENDER: 'gender',
        TOTAL: 'total/',
        NEWSLETTER: 'newsletter/',
        REGISTER: 'register',
        UPDATEUSER: 'updateUser',
        UPDATEBILLING: 'updateBilling',
        UPDATEDELIVERY: 'updateDelivery',
        DELETEUSER: 'deleteUser',
        CHECKOUT: 'checkout',
        UPDATEPASSWORD: 'updatePassword/',
        CONTACT: 'contact/',
        ORDERS: 'orders/',
        ADDRESS: 'address',
        RESET: 'reset/',
        REQUEST: 'request/',
        SEARCH: 'search/',
        AUTOCOMPLETE: 'autocomplete/',
        BOXES: 'boxes/',
        BANNER_TEXT: 'bannerText/',
        IMAGES: 'images/',
        HEADER_MESSAGE: 'headerMessage/',
        AGREEMENT: 'agreement/',
        PROMO: 'promo/'
    }
}


export default Constant